### ISSUE TITLE
Pathfinder 2: Monsterhandbuch I & II & III

### ISSUE THREAD

**Issue by Grimmerling** [Foundry-VTT-PF2-German/premium-modules#1]
Trying to install above mentioned modules' versions 5.16.0.1 as Bazaar install page suggests; 6.0.1 is installed instead. That one is not compatible with Foundry 11. 
![Screenshot 2024-06-23 124524](https://github.com/Foundry-VTT-PF2-German/premium-modules/assets/68050750/1fa942ae-555e-4e28-bff6-b74f49496c79)
Please fix or provide manifest URL!
Manifest URLs 5.15.1 and upwards on Foundry VTT page are broken, too.

**Comment by MSAbaddon** [comment]
Kannst du es bitte nochmals versuchen und kurz Rückmeldung geben, ob jetzt korrekt Version 5.16.1.0 installiert wird?

**Comment by Grimmerling** [comment]
Hat funktioniert. Vielen Dank!
